# Generated by Django 3.2.5 on 2021-07-27 03:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('modalidade', models.CharField(choices=[('RENDA FIXA', 'RENDA FIXA'), ('RENDA VARIAVEL', 'RENDA VARIAVEL'), ('CRIPTO', 'CRIPTO')], max_length=15)),
                ('preco_mercado_em_centavos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Taxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('percentual', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(choices=[('APLICACAO', 'APLICACAO'), ('RESGATE', 'RESGATE')], max_length=10)),
                ('data_de_solicitacao', models.DateField(auto_now_add=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario_em_centavos', models.PositiveIntegerField()),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
