# Generated by Django 3.2.5 on 2021-07-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='modalidade',
            field=models.CharField(choices=[('F', 'RENDA FIXA'), ('V', 'RENDA VARIAVEL'), ('C', 'CRIPTOMOEDA')], max_length=50),
        ),
    ]
