# Generated by Django 3.2.5 on 2021-07-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ativo_modalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='modalidade',
            field=models.CharField(choices=[('RENDA FIXA', 'RENDA FIXA'), ('RENDA VARIAVEL', 'RENDA VARIAVEL'), ('CRIPTO', 'CRIPTO')], max_length=50),
        ),
    ]
