# Generated by Django 3.2.5 on 2021-07-22 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_aplicacao_resgate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(choices=[('APLICACAO', 'APLICACAO'), ('RESGATE', 'RESGATE')], max_length=10)),
                ('data_de_solicitacao', models.DateField(auto_now_add=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario_em_centavos', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resgate',
            name='ativo',
        ),
        migrations.AlterField(
            model_name='ativo',
            name='modalidade',
            field=models.CharField(choices=[('RENDA FIXA', 'RENDA FIXA'), ('RENDA VARIAVEL', 'RENDA VARIAVEL'), ('CRIPTO', 'CRIPTO')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Aplicacao',
        ),
        migrations.DeleteModel(
            name='Resgate',
        ),
        migrations.AddField(
            model_name='operacao',
            name='ativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.ativo'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
