# Generated by Django 3.2.5 on 2021-07-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210722_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='endereco_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
