from django.test import TestCase

# Como um USUÁRIO eu gostaria de CADASTRAR UM ATIVO para REALIZAR APLICACOES OU RESGATES.
# Como um USUÁRIO eu gostaria de FAZER APLICACOES E RESGATES EM UM ATIVO para INICIAR UM INVESTIMENTO.
# Como um USUÁRIO eu gostaria de VISUALIZAR O SALDO DA MINHA CARTEIRA DE INVESTIMENTOS para ACOMPANHAR OS RESULTADOS DO MEU INVESTIMENTO
